
#include <stdio.h>
#include <liboil/liboil.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>

#include <liboil/liboilprototype.h>

void print_header (void);
void print_footer (void);

int main (int argc, char *argv[])
{
  OilFunctionClass *klass;
  OilFunctionImpl *impl;
  int i;

  oil_init ();

  print_header ();

  printf ("#include <liboil/liboilfunction.h>\n");
  printf ("\n");
  for (i=0;i<oil_n_function_classes; i++ ){
    klass = oil_class_get_by_index (i);

    printf ("extern OilFunctionClass _oil_function_class_%s;\n", klass->name);
  }
  printf ("\n");
  printf ("OilFunctionClass *_oil_function_class_array[] = {\n");
  for (i=0;i<oil_n_function_classes; i++ ){
    klass = oil_class_get_by_index (i);

    printf ("\t&_oil_function_class_%s,\n", klass->name);
  }
  printf ("\tNULL\n");
  printf ("};\n");
  printf ("\n");
  for (i=0;i<oil_n_function_impls; i++ ){
    impl = oil_impl_get_by_index (i);

    printf ("extern OilFunctionImpl _oil_function_impl_%s;\n", impl->name);
  }
  printf ("\n");
  printf ("OilFunctionImpl *_oil_function_impl_array[] = {\n");
  for (i=0;i<oil_n_function_impls; i++ ){
    impl = oil_impl_get_by_index (i);

    printf ("\t&_oil_function_impl_%s,\n", impl->name);
  }
  printf ("\tNULL\n");
  printf ("};\n");
  printf ("\n");

  return 0;
}

void print_header (void)
{
  printf ("/* liboil - Library of Optimized Inner Loops\n");
  printf (" * Copyright (C) 2003  David A. Schleef <ds@schleef.org>\n");
  printf (" *\n");
  printf (" * This library is free software; you can redistribute it and/or\n");
  printf (" * modify it under the terms of version 2.1 of the GNU Lesser General\n");
  printf (" * Public License as published by the Free Software Foundation.\n");
  printf (" *\n");
  printf (" * This library is distributed in the hope that it will be useful,\n");
  printf (" * but WITHOUT ANY WARRANTY; without even the implied warranty of\n");
  printf (" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n");
  printf (" * Library General Public License for more details.\n");
  printf (" *\n");
  printf (" * You should have received a copy of the GNU Lesser General Public\n");
  printf (" * License along with this library; if not, write to the\n");
  printf (" * Free Software Foundation, Inc., 59 Temple Place, Suite 330,\n");
  printf (" * Boston, MA 02111-1307 USA.\n");
  printf (" */\n");
  printf ("\n");
  printf ("/* This file is automatically generated.  Do not edit. */\n");
  printf ("\n");
}

